sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.6.5
  - ghc: 8.8.3
  - ghc: 8.10.1

  # stack
  - ghc: 8.8.3
  - ghc: 8.10.1
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal haddock
      cabal test all --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
